# Copyright (C) 2026 Maxim [maxirmx] Samsonov (www.sw.consulting)
# All rights reserved.
# This file is a part of the Sarafan application

services:
  backoffice:
    networks:
      default:
      edge:
        aliases:
          - sarafan-backoffice
  ui:
    networks:
      edge:
        aliases:
          - sarafan-ui

networks:
  edge:
    name: ${SW_CONSULTING_EDGE_NETWORK:-sw-consulting-edge}
    external: true
