// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sarafan.Core.Data;

#nullable disable

namespace Sarafan.Core.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924171050_0_3_0_ServiceCatalogue")]
    partial class _0_3_0_ServiceCatalogue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sarafan.Core.Models.BackofficeRefreshSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BackofficeUserId")
                        .HasColumnType("integer")
                        .HasColumnName("backoffice_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_agent");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("BackofficeUserId", "FamilyId");

                    b.ToTable("backoffice_refresh_sessions", (string)null);
                });

            modelBuilder.Entity("Sarafan.Core.Models.BackofficeRole", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_name");

                    b.HasKey("Code");

                    b.ToTable("backoffice_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "administrator",
                            DisplayName = "Administrator"
                        },
                        new
                        {
                            Code = "shift-manager",
                            DisplayName = "Shift manager"
                        },
                        new
                        {
                            Code = "senior-operator",
                            DisplayName = "Senior operator"
                        },
                        new
                        {
                            Code = "operator",
                            DisplayName = "Operator"
                        });
                });

            modelBuilder.Entity("Sarafan.Core.Models.BackofficeUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDemo")
                        .HasColumnType("boolean")
                        .HasColumnName("is_demo");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("patronymic");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("integer")
                        .HasColumnName("token_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("backoffice_users", (string)null);
                });

            modelBuilder.Entity("Sarafan.Core.Models.BackofficeUserRole", b =>
                {
                    b.Property<int>("BackofficeUserId")
                        .HasColumnType("integer")
                        .HasColumnName("backoffice_user_id");

                    b.Property<string>("RoleCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role_code");

                    b.HasKey("BackofficeUserId", "RoleCode");

                    b.HasIndex("RoleCode");

                    b.ToTable("backoffice_user_roles", (string)null);
                });

            modelBuilder.Entity("Sarafan.Core.Models.ConsentEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("decision");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("RetainUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retain_until");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<string>("SubjectKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("subject_key");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("SubjectKey", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("CustomerId", "Kind", "Id");

                    b.ToTable("consent_events", (string)null);
                });

            modelBuilder.Entity("Sarafan.Core.Models.ConsentOnboarding", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("Flow")
                        .HasColumnType("integer")
                        .HasColumnName("flow");

                    b.Property<Guid?>("PersonalDataDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_data_document_id");

                    b.Property<string>("PersonalDataHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("personal_data_hash");

                    b.Property<Guid?>("PersonalDataIdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_data_idempotency_key");

                    b.Property<string>("PhoneHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("phone_hash");

                    b.Property<int?>("TargetCustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("target_customer_id");

                    b.Property<bool>("TermsAccepted")
                        .HasColumnType("boolean")
                        .HasColumnName("terms_accepted");

                    b.Property<Guid>("TermsDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("terms_document_id");

                    b.Property<string>("TermsHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("terms_hash");

                    b.Property<Guid?>("TermsIdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("terms_idempotency_key");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("TokenHash");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("PersonalDataDocumentId");

                    b.HasIndex("TargetCustomerId");

                    b.HasIndex("TermsDocumentId");

                    b.ToTable("consent_onboarding", null, t =>
                        {
                            t.HasCheckConstraint("ck_consent_onboarding_flow", "(flow = 1 AND target_customer_id IS NOT NULL AND personal_data_document_id IS NULL AND personal_data_hash IS NULL AND personal_data_idempotency_key IS NULL AND terms_accepted AND terms_idempotency_key IS NOT NULL) OR (flow = 2 AND personal_data_document_id IS NOT NULL AND personal_data_hash IS NOT NULL AND personal_data_idempotency_key IS NOT NULL AND ((terms_accepted AND terms_idempotency_key IS NOT NULL) OR (NOT terms_accepted AND terms_idempotency_key IS NULL)))");
                        });
                });

            modelBuilder.Entity("Sarafan.Core.Models.ConsentReplayTombstone", b =>
                {
                    b.Property<string>("KeyHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_hash");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.HasKey("KeyHash");

                    b.HasIndex("DocumentId");

                    b.ToTable("consent_replay_tombstones", (string)null);
                });

            modelBuilder.Entity("Sarafan.Core.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("NextOrderNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("next_order_number");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("order_code");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("phone");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<int>("TokenVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("token_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrderCode")
                        .IsUnique()
                        .HasDatabaseName("ux_customers_order_code")
                        .HasFilter("order_code IS NOT NULL");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("customers", null, t =>
                        {
                            t.HasCheckConstraint("ck_customers_next_order_number", "next_order_number > 0");

                            t.HasCheckConstraint("ck_customers_order_code", "order_code IS NULL OR order_code ~ '^[0-9]{8}$'");

                            t.HasCheckConstraint("ck_customers_phone_russian", "phone ~ '^\\+7[0-9]{10}$'");

                            t.HasCheckConstraint("ck_customers_state", "state IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("Sarafan.Core.Models.CustomerConsentWithdrawalRequest", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<bool>("Processed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("processed");

                    b.HasKey("CustomerId", "RequestedAt");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasFilter("processed = FALSE");

                    b.HasIndex("Processed", "RequestedAt", "CustomerId")
                        .IsDescending(false, true, false)
                        .HasDatabaseName("IX_customer_consent_withdrawal_requests_queue");

                    b.ToTable("customer_consent_withdrawal_requests", (string)null);
                });

            modelBuilder.Entity("Sarafan.Core.Models.CustomerPhoto", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<int>("Size")
                        .HasColumnType("integer")
                        .HasColumnName("size");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("CustomerId");

                    b.ToTable("customer_photos", (string)null);
                });

            modelBuilder.Entity("Sarafan.Core.Models.CustomerProfile", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("city");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("Inn")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("inn");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<DateOnly?>("PassportIssueDate")
                        .HasColumnType("date")
                        .HasColumnName("passport_issue_date");

                    b.Property<string>("PassportIssuedBy")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("passport_issued_by");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("passport_number");

                    b.Property<string>("PassportSeries")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("passport_series");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("patronymic");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postal_code");

                    b.HasKey("CustomerId");

                    b.ToTable("customer_profiles", (string)null);
                });

            modelBuilder.Entity("Sarafan.Core.Models.ExchangeRateHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BaseCurrency")
                        .HasColumnType("integer")
                        .HasColumnName("base_currency");

                    b.Property<int>("Nominal")
                        .HasColumnType("integer")
                        .HasColumnName("nominal");

                    b.Property<decimal>("OfficialRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("official_rate");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("provider");

                    b.Property<int>("QuoteCurrency")
                        .HasColumnType("integer")
                        .HasColumnName("quote_currency");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source");

                    b.Property<DateOnly>("SourceEffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("source_effective_date");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "BaseCurrency", "QuoteCurrency", "SourceEffectiveDate")
                        .IsUnique();

                    b.ToTable("exchange_rate_history", null, t =>
                        {
                            t.HasCheckConstraint("CK_exchange_rate_base_currency", "base_currency IN (643, 840, 978)");

                            t.HasCheckConstraint("CK_exchange_rate_distinct_currencies", "base_currency <> quote_currency");

                            t.HasCheckConstraint("CK_exchange_rate_nominal", "nominal BETWEEN 1 AND 1000000");

                            t.HasCheckConstraint("CK_exchange_rate_positive", "official_rate > 0");

                            t.HasCheckConstraint("CK_exchange_rate_quote_currency", "quote_currency IN (643, 840, 978)");
                        });
                });

            modelBuilder.Entity("Sarafan.Core.Models.IanaTldCatalog", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<string>("ContentSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_sha256");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("SourceUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_updated_at");

                    b.PrimitiveCollection<string[]>("TopLevelDomains")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("top_level_domains");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("iana_tld_catalog", null, t =>
                        {
                            t.HasCheckConstraint("ck_iana_tld_catalog_content_sha256", "content_sha256 ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_iana_tld_catalog_not_empty", "cardinality(top_level_domains) > 0");

                            t.HasCheckConstraint("ck_iana_tld_catalog_singleton", "id = 1");

                            t.HasCheckConstraint("ck_iana_tld_catalog_version", "version ~ '^[0-9]{10}$'");
                        });
                });

            modelBuilder.Entity("Sarafan.Core.Models.LegalDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_version");

                    b.Property<DateTimeOffset>("EffectiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_at");

                    b.Property<string>("Html")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("html");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("locale");

                    b.Property<string>("RendererVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("renderer_version");

                    b.Property<byte[]>("Source")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("source");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_hash");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "Locale", "DisplayVersion")
                        .IsUnique();

                    b.HasIndex("Kind", "Locale", "EffectiveAt")
                        .IsUnique();

                    b.ToTable("legal_documents", (string)null);
                });

            modelBuilder.Entity("Sarafan.Core.Models.LegalDocumentAuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("action");

                    b.Property<int>("ActorId")
                        .HasColumnType("integer")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("DisplayVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_version");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<DateTimeOffset>("EffectiveAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_at");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("locale");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_hash");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("At", "Id");

                    b.ToTable("legal_document_audit_events", (string)null);
                });

            modelBuilder.Entity("Sarafan.Core.Models.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AppliedExchangeRateHistoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("applied_exchange_rate_history_id");

                    b.Property<string>("Characteristics")
                        .HasColumnType("jsonb")
                        .HasColumnName("characteristics");

                    b.Property<string>("Color")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("color");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreationIdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("creation_idempotency_key");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<long>("CustomerOrderNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_order_number");

                    b.Property<decimal?>("HeightCm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("height_cm");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<decimal?>("LengthCm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("length_cm");

                    b.Property<string>("ProductName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("SellerPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("seller_price");

                    b.Property<int?>("SellerPriceCurrency")
                        .HasColumnType("integer")
                        .HasColumnName("seller_price_currency");

                    b.Property<string>("Size")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("size");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_url");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<string>("StoreName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("store_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("WidthCm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("width_cm");

                    b.HasKey("Id");

                    b.HasIndex("AppliedExchangeRateHistoryId")
                        .HasDatabaseName("ix_orders_applied_exchange_rate_history_id");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("ix_orders_created_at_id");

                    b.HasIndex("CustomerId", "CreationIdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_orders_creation_idempotency");

                    b.HasIndex("CustomerId", "CustomerOrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_orders_customer_order_number");

                    b.HasIndex("UpdatedAt", "Id")
                        .HasDatabaseName("ix_orders_updated_at_id");

                    b.HasIndex("Status", "CreatedAt", "Id")
                        .HasDatabaseName("ix_orders_status_created_at_id");

                    b.ToTable("orders", null, t =>
                        {
                            t.HasCheckConstraint("ck_orders_applied_exchange_rate", "applied_exchange_rate_history_id IS NULL OR seller_price_currency IS NOT NULL");

                            t.HasCheckConstraint("ck_orders_creation_idempotency_key", "creation_idempotency_key <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_orders_customer_order_number", "customer_order_number > 0");

                            t.HasCheckConstraint("ck_orders_dimensions", "(length_cm IS NULL AND width_cm IS NULL AND height_cm IS NULL) OR (length_cm > 0 AND width_cm > 0 AND height_cm > 0)");

                            t.HasCheckConstraint("ck_orders_image_url", "image_url IS NULL OR image_url ~* '^https?://' AND char_length(image_url) <= 2048");

                            t.HasCheckConstraint("ck_orders_quantity", "quantity > 0");

                            t.HasCheckConstraint("ck_orders_seller_price", "(seller_price IS NULL AND seller_price_currency IS NULL) OR (seller_price > 0 AND seller_price_currency IN (643, 840, 978))");

                            t.HasCheckConstraint("ck_orders_source_url", "source_url ~* '^https?://' AND char_length(source_url) <= 2048");

                            t.HasCheckConstraint("ck_orders_status", "status IN (0, 100, 200, 300, 310, 320, 330, 340, 360, 380, 400, 500)");
                        });
                });

            modelBuilder.Entity("Sarafan.Core.Models.OrderPricingSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("ActorId")
                        .HasColumnType("integer")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorName")
                        .HasMaxLength(605)
                        .HasColumnType("character varying(605)")
                        .HasColumnName("actor_name");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("OrderId", "Id")
                        .HasDatabaseName("ix_order_pricing_order_id");

                    b.ToTable("order_pricing_snapshots", null, t =>
                        {
                            t.HasCheckConstraint("ck_order_pricing_actor", "(actor_id IS NULL AND actor_name IS NULL) OR (actor_id IS NOT NULL AND actor_name IS NOT NULL AND btrim(actor_name) <> '')");

                            t.HasCheckConstraint("ck_order_pricing_validity", "valid_until IS NULL OR valid_until > at");
                        });
                });

            modelBuilder.Entity("Sarafan.Core.Models.OrderProductAuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("ActorId")
                        .HasColumnType("integer")
                        .HasColumnName("actor_id");

                    b.Property<string>("After")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("after");

                    b.Property<string>("Before")
                        .HasColumnType("jsonb")
                        .HasColumnName("before");

                    b.Property<long?>("EurRateId")
                        .HasColumnType("bigint")
                        .HasColumnName("eur_rate_id");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<long?>("UsdRateId")
                        .HasColumnType("bigint")
                        .HasColumnName("usd_rate_id");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("EurRateId");

                    b.HasIndex("UsdRateId");

                    b.HasIndex("OrderId", "Kind");

                    b.HasIndex("OrderId", "OccurredAt");

                    b.ToTable("order_product_audit_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_order_product_audit_kind", "kind IN (0, 100, 200)");

                            t.HasCheckConstraint("ck_order_product_audit_rate_pair", "(usd_rate_id IS NULL) = (eur_rate_id IS NULL)");

                            t.HasCheckConstraint("ck_order_product_audit_source", "(kind = 200 AND actor_id IS NOT NULL AND before IS NOT NULL AND usd_rate_id IS NOT NULL) OR (kind IN (0, 100) AND actor_id IS NULL)");
                        });
                });

            modelBuilder.Entity("Sarafan.Core.Models.RefreshSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by_ip");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_agent");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("CustomerId", "FamilyId");

                    b.ToTable("refresh_sessions", (string)null);
                });

            modelBuilder.Entity("Sarafan.Core.Models.ServiceCatalogueAuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<int>("ActorId")
                        .HasColumnType("integer")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(605)
                        .HasColumnType("character varying(605)")
                        .HasColumnName("actor_name");

                    b.Property<string>("After")
                        .HasColumnType("jsonb")
                        .HasColumnName("after");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Before")
                        .HasColumnType("jsonb")
                        .HasColumnName("before");

                    b.Property<long>("EntryId")
                        .HasColumnType("bigint")
                        .HasColumnName("entry_id");

                    b.Property<int>("Service")
                        .HasColumnType("integer")
                        .HasColumnName("service");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("At", "Id")
                        .HasDatabaseName("ix_service_catalogue_audit_at_id");

                    b.HasIndex("EntryId", "At", "Id")
                        .HasDatabaseName("ix_service_catalogue_audit_entry_at_id");

                    b.HasIndex("Service", "At", "Id")
                        .HasDatabaseName("ix_service_catalogue_audit_service_at_id");

                    b.ToTable("service_catalogue_audit_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_service_catalogue_audit_action", "action IN (0, 100, 200)");

                            t.HasCheckConstraint("ck_service_catalogue_audit_actor_name", "btrim(actor_name) <> ''");

                            t.HasCheckConstraint("ck_service_catalogue_audit_service", "service IN (0, 100, 200, 300, 400, 500, 600, 700)");

                            t.HasCheckConstraint("ck_service_catalogue_audit_snapshots", "(action = 0 AND before IS NULL AND after IS NOT NULL)\r\nOR (action = 100 AND before IS NOT NULL AND after IS NOT NULL)\r\nOR (action = 200 AND before IS NOT NULL AND after IS NULL)");
                        });
                });

            modelBuilder.Entity("Sarafan.Core.Models.ServiceCatalogueEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateOnly?>("AvailableBy")
                        .HasColumnType("date")
                        .HasColumnName("available_by");

                    b.Property<DateOnly?>("AvailableFrom")
                        .HasColumnType("date")
                        .HasColumnName("available_from");

                    b.Property<string>("Bands")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("bands");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("Currency")
                        .HasColumnType("integer")
                        .HasColumnName("currency");

                    b.Property<int?>("IntervalCurrency")
                        .HasColumnType("integer")
                        .HasColumnName("interval_currency");

                    b.Property<decimal?>("MaximumAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("maximum_amount");

                    b.Property<decimal?>("MinimumAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("minimum_amount");

                    b.Property<decimal?>("Percentage")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("percentage");

                    b.Property<int>("PriceMethod")
                        .HasColumnType("integer")
                        .HasColumnName("price_method");

                    b.Property<int>("Service")
                        .HasColumnType("integer")
                        .HasColumnName("service");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Service", "AvailableFrom", "Id")
                        .HasDatabaseName("ix_service_catalogue_service_available_from_id");

                    b.ToTable("service_catalogue_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_service_catalogue_bands", "(price_method = 400 AND interval_currency IS NOT NULL AND interval_currency = 840 AND valid_service_price_bands(bands)) OR (price_method <> 400 AND interval_currency IS NULL AND bands = '[]'::jsonb)");

                            t.HasCheckConstraint("ck_service_catalogue_currency", "currency IS NOT NULL AND currency IN (643, 840)");

                            t.HasCheckConstraint("ck_service_catalogue_method", "price_method IN (0, 100, 200, 300, 400)");

                            t.HasCheckConstraint("ck_service_catalogue_parameters", "(price_method = 0 AND percentage IS NOT NULL AND percentage > 0 AND percentage <= 100\r\n    AND amount IS NULL AND currency = 840\r\n    AND (minimum_amount IS NULL OR minimum_amount >= 0)\r\n    AND (maximum_amount IS NULL OR maximum_amount >= 0)\r\n    AND (minimum_amount IS NULL OR maximum_amount IS NULL OR maximum_amount >= minimum_amount))\r\nOR (price_method = 100 AND percentage IS NULL AND minimum_amount IS NULL AND maximum_amount IS NULL\r\n    AND amount IS NOT NULL AND amount >= 0 AND currency IN (643, 840))\r\nOR (price_method IN (200, 300, 400) AND percentage IS NULL AND minimum_amount IS NULL AND maximum_amount IS NULL\r\n    AND amount IS NULL AND currency IN (643, 840))");

                            t.HasCheckConstraint("ck_service_catalogue_period", "available_from IS NULL OR available_by IS NULL OR available_by >= available_from");

                            t.HasCheckConstraint("ck_service_catalogue_product_identity", "(service = 0 AND id = 1) OR (service <> 0 AND id <> 1)");

                            t.HasCheckConstraint("ck_service_catalogue_service", "service IN (0, 100, 200, 300, 400, 500, 600, 700)");

                            t.HasCheckConstraint("ck_service_catalogue_timestamps", "updated_at >= created_at");

                            t.HasCheckConstraint("ck_service_catalogue_version", "version <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("Sarafan.Core.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("OfficialUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("official_url");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_stores_display_order");

                    b.HasIndex("Status", "DisplayOrder", "Id")
                        .HasDatabaseName("ix_stores_status_display_order_id");

                    b.ToTable("stores", null, t =>
                        {
                            t.HasCheckConstraint("ck_stores_description", "btrim(description) <> ''");

                            t.HasCheckConstraint("ck_stores_display_order", "display_order >= 0");

                            t.HasCheckConstraint("ck_stores_name", "btrim(name) <> ''");

                            t.HasCheckConstraint("ck_stores_official_url", "official_url ~* '^https?://'");

                            t.HasCheckConstraint("ck_stores_status", "status IN (0, 1, 2)");

                            t.HasCheckConstraint("ck_stores_timestamps", "updated_at >= created_at");

                            t.HasCheckConstraint("ck_stores_version", "version <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("Sarafan.Core.Models.StoreLogo", b =>
                {
                    b.Property<int>("StoreId")
                        .HasColumnType("integer")
                        .HasColumnName("store_id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.Property<string>("ContentSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_sha256");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_type");

                    b.HasKey("StoreId");

                    b.ToTable("store_logos", null, t =>
                        {
                            t.HasCheckConstraint("ck_store_logos_content_sha256", "content_sha256 ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_store_logos_content_size", "octet_length(content) BETWEEN 1 AND 2097152");

                            t.HasCheckConstraint("ck_store_logos_content_type", "content_type IN ('image/png', 'image/jpeg', 'image/webp')");
                        });
                });

            modelBuilder.Entity("Sarafan.Core.Models.BackofficeRefreshSession", b =>
                {
                    b.HasOne("Sarafan.Core.Models.BackofficeUser", "BackofficeUser")
                        .WithMany("RefreshSessions")
                        .HasForeignKey("BackofficeUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BackofficeUser");
                });

            modelBuilder.Entity("Sarafan.Core.Models.BackofficeUserRole", b =>
                {
                    b.HasOne("Sarafan.Core.Models.BackofficeUser", "BackofficeUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("BackofficeUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sarafan.Core.Models.BackofficeRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BackofficeUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Sarafan.Core.Models.ConsentEvent", b =>
                {
                    b.HasOne("Sarafan.Core.Models.Customer", null)
                        .WithMany("ConsentEvents")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sarafan.Core.Models.LegalDocument", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Sarafan.Core.Models.ConsentOnboarding", b =>
                {
                    b.HasOne("Sarafan.Core.Models.LegalDocument", null)
                        .WithMany()
                        .HasForeignKey("PersonalDataDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sarafan.Core.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("TargetCustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sarafan.Core.Models.LegalDocument", null)
                        .WithMany()
                        .HasForeignKey("TermsDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sarafan.Core.Models.ConsentReplayTombstone", b =>
                {
                    b.HasOne("Sarafan.Core.Models.LegalDocument", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sarafan.Core.Models.CustomerConsentWithdrawalRequest", b =>
                {
                    b.HasOne("Sarafan.Core.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sarafan.Core.Models.CustomerPhoto", b =>
                {
                    b.HasOne("Sarafan.Core.Models.Customer", "Customer")
                        .WithOne("Photo")
                        .HasForeignKey("Sarafan.Core.Models.CustomerPhoto", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Sarafan.Core.Models.CustomerProfile", b =>
                {
                    b.HasOne("Sarafan.Core.Models.Customer", "Customer")
                        .WithOne("Profile")
                        .HasForeignKey("Sarafan.Core.Models.CustomerProfile", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Sarafan.Core.Models.LegalDocumentAuditEvent", b =>
                {
                    b.HasOne("Sarafan.Core.Models.BackofficeUser", "BackofficeUser")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BackofficeUser");
                });

            modelBuilder.Entity("Sarafan.Core.Models.Order", b =>
                {
                    b.HasOne("Sarafan.Core.Models.ExchangeRateHistory", "AppliedExchangeRateHistory")
                        .WithMany()
                        .HasForeignKey("AppliedExchangeRateHistoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sarafan.Core.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppliedExchangeRateHistory");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Sarafan.Core.Models.OrderPricingSnapshot", b =>
                {
                    b.HasOne("Sarafan.Core.Models.BackofficeUser", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sarafan.Core.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Sarafan.Core.Models.OrderProductAuditEvent", b =>
                {
                    b.HasOne("Sarafan.Core.Models.BackofficeUser", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sarafan.Core.Models.ExchangeRateHistory", null)
                        .WithMany()
                        .HasForeignKey("EurRateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sarafan.Core.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sarafan.Core.Models.ExchangeRateHistory", null)
                        .WithMany()
                        .HasForeignKey("UsdRateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Sarafan.Core.Models.RefreshSession", b =>
                {
                    b.HasOne("Sarafan.Core.Models.Customer", "Customer")
                        .WithMany("RefreshSessions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Sarafan.Core.Models.ServiceCatalogueAuditEvent", b =>
                {
                    b.HasOne("Sarafan.Core.Models.BackofficeUser", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("Sarafan.Core.Models.StoreLogo", b =>
                {
                    b.HasOne("Sarafan.Core.Models.Store", "Store")
                        .WithOne("Logo")
                        .HasForeignKey("Sarafan.Core.Models.StoreLogo", "StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Sarafan.Core.Models.BackofficeRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Sarafan.Core.Models.BackofficeUser", b =>
                {
                    b.Navigation("RefreshSessions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Sarafan.Core.Models.Customer", b =>
                {
                    b.Navigation("ConsentEvents");

                    b.Navigation("Orders");

                    b.Navigation("Photo");

                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("RefreshSessions");
                });

            modelBuilder.Entity("Sarafan.Core.Models.Store", b =>
                {
                    b.Navigation("Logo");
                });
#pragma warning restore 612, 618
        }
    }
}
